WITH src AS (
  SELECT
    EMPLOYEE_ID,
    REPORT_DATE,
    HR_EMPLOYEE_STATUS_DESC
  FROM TABLE
  WHERE REPORT_DATE >= '2025-10-01'
    AND REPORT_DATE <= '2025-10-31'
),

ordered AS (
  SELECT
    EMPLOYEE_ID,
    REPORT_DATE,
    HR_EMPLOYEE_STATUS_DESC,
    LAG(HR_EMPLOYEE_STATUS_DESC)
      OVER (PARTITION BY EMPLOYEE_ID ORDER BY REPORT_DATE) AS PREV_STATUS,
    LAG(REPORT_DATE)
      OVER (PARTITION BY EMPLOYEE_ID ORDER BY REPORT_DATE) AS PREV_DATE,
    MAX(REPORT_DATE)
      OVER (PARTITION BY EMPLOYEE_ID) AS LAST_UPDATE_DATE
  FROM src
)

SELECT
  EMPLOYEE_ID,
  -- start date of this status segment
  IF(PREV_STATUS IS NULL OR PREV_STATUS != HR_EMPLOYEE_STATUS_DESC,
     REPORT_DATE,
     NULL) AS HR_EMPLOYEE_STATUS_START_DATE,

  HR_EMPLOYEE_STATUS_DESC,

  -- end date of the segment
  LEAD(REPORT_DATE)
    OVER (PARTITION BY EMPLOYEE_ID ORDER BY REPORT_DATE) - 1
      AS HR_EMPLOYEE_STATUS_END_DATE

FROM ordered

-- keep only segment-start rows
WHERE PREV_STATUS IS NULL OR PREV_STATUS != HR_EMPLOYEE_STATUS_DESC

ORDER BY EMPLOYEE_ID, HR_EMPLOYEE_STATUS_START_DATE;
