WITH src AS (
  SELECT
    EMPLOYEE_ID,
    REPORT_DATE,
    HR_EMPLOYEE_STATUS_DESC
  FROM TABLE
  WHERE REPORT_DATE >= '2025-10-01'
    AND REPORT_DATE <= '2025-10-31'
),

ordered AS (
  SELECT
    EMPLOYEE_ID,
    REPORT_DATE,
    HR_EMPLOYEE_STATUS_DESC,
    LAG(HR_EMPLOYEE_STATUS_DESC)
      OVER (PARTITION BY EMPLOYEE_ID ORDER BY REPORT_DATE) AS PREV_STATUS,
    LEAD(REPORT_DATE)
      OVER (PARTITION BY EMPLOYEE_ID ORDER BY REPORT_DATE) AS NEXT_DATE
  FROM src
)

SELECT
  EMPLOYEE_ID,
  REPORT_DATE AS HR_EMPLOYEE_STATUS_START_DATE,
  HR_EMPLOYEE_STATUS_DESC,
  NEXT_DATE AS HR_EMPLOYEE_STATUS_END_DATE
FROM ordered
WHERE PREV_STATUS IS NULL OR PREV_STATUS != HR_EMPLOYEE_STATUS_DESC
ORDER BY EMPLOYEE_ID, HR_EMPLOYEE_STATUS_START_DATE;
