WITH
  identify_changes AS (
    SELECT
      EMPLOYEE_ID,
      REPORT_DATE,
      HR_EMPLOYEE_STATUS_DESC,
      LAG(HR_EMPLOYEE_STATUS_DESC) OVER (PARTITION BY EMPLOYEE_ID ORDER BY REPORT_DATE) AS prev_status
      FROM `hsbc-11359979-dbsrefinery-prod.shared_data_assets_archive_released_prod.DA_WPB_RESOURCE_AGILE_TEAM_MAPPING_ARCHIVE`
      WHERE REPORT_DATE >= '2025-10-01' AND REPORT DATE <= '2025-10-31'
      AND HR_L2_OSPD_NAME IN ('IWPB Technology', 'UK Technology')),

  assign_segment_groups AS (
    SELECT
      *, SUM(
        CASE
          WHEN HR_EMPLOYEE_STATUS_DESC != prev_status THEN 1
          WHEN prev_status IS NULL THEN 1
          ELSE 0
          END) OVER (PARTITION BY EMPLOYEE_ID ORDER BY REPORT_DATE) AS segment_group
    FROM identify_changes)
SELECT
  EMPLOYEE_ID,
  MIN(REPORT_DATE) AS HR_EMPLOYEE_STATUS_START_DATE,
  HR_EMPLOYEE_STATUS_DESC,
  MAX(REPORT_DATE) AS HR_EMPLOYEE_STATUS_END_DATE
FROM
  assign_segment_groups
GROUP BY
  EMPLOYEE_ID,
  HR_EMPLOYEE_STATUS_DESC,
  segment_group
ORDER BY
  EMPLOYEE_ID,
  HR_EMPLOYEE_STATUS_START_DATE;
